server:
  port: 8088

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:54321/db_coffeshop
    username: user
    password: user

bezkoder:
      app:
          jwtCookieName: bezkoder
           jwtSecret: spring
                jwtExpirationMs: 86400000